language: rust

env:
    global:
        secure: "c2p6nlj/gl/X9jifSk4NfuPl3RF1lAtXu2r/81+J7Q5sj6x4x5THUGIb/GU4TQ6G0i8bkOUOi9fk1D3BRrnQlNhokXK+/p/FBuFcKXT8kNOKGo9paCI8tztpDLZyamor3Q9/lpoQSJXjlyJrIsHBMcDZAqjgeOKX3XZGDki79EjDghOCaW9cBpVEup2vwd1E1nH3hBClaIYHlPehn9pNJ1kCw5conZ1IADSCddkfUUb+pk77CIxGYPf9wko9z7crQZm/o2bbhnoEbAsHoaez3zpN5EXOI7WJQVBjQlEPIAjhFS+4XiGyF9WB9TgL/S5x51yUbNZOhZ96VnSHa7c/zxiIq3iG0wUHy+zmPwK34JgL0fMu6CWrxipUSUQirDWUro8l42exTNO75/XqVNbAxs4dPfbOXq3ICIC+56fXh5yXyRj3xg1rmb0EvqX3cxk9npXx25mRh5kRFIfwpnqVcyeNGUHtbyJ/mfvC59x9jcAKy5eZZzDoBbExbuBMVhptULscE1g2ZQgwG55+yMSfka8nH+4BZzobyqJwiDYvQ0b7211ejVd42Rq14GCZpNcipttOeue8lnyvuJgrUtK3U7bVALUym1IDYjGKcCKuLi3XaEe9EiWOrAC38qtoG5OtJYnwFyZVIpMqpBlv8GynUy8m7wQW1PgEAAUCaEGrkIA="

script:
    - cargo build
    - cargo test
    - cargo doc --no-deps

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    echo '<meta http-equiv=refresh content=0;url=thread_isolated/index.html>' > target/doc/index.html &&
    sudo pip install ghp-import &&
    ghp-import -n target/doc &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
